apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 2  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.15.1
          ports:
            - containerPort: 5044

---

apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  selector:
    app: logstash # Match this label with the Pod's labels
  ports:
    - protocol: TCP
      port: 5044
      targetPort: 5044

