apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'frontend'
        static_configs:
          - targets: ['frontend-service:80'] # Adjust the target as per your service name and port
        metrics_path: /metrics

      - job_name: 'backend'
        static_configs:
          - targets: ['backend-service:5000'] # Adjust the target as per your service name and port
        metrics_path: /metrics

      - job_name: 'database'
        static_configs:
          - targets: ['database-service:3306'] # Adjust the target as per your service name and port
        metrics_path: /metrics

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
