# role-definition.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: your-namespace
  name: role-name
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "create", "delete"]
 

---

# role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-name
  namespace: your-namespace
subjects:
- kind: User
  name: username
roleRef:
  kind: Role
  name: role-name
  apiGroup: rbac.authorization.k8s.io


